
Import('env')

env.Replace(LIBS=[])

env.Program(
    target="algorithms/spatial_indexing/tst_quadtree", 
    source="algorithms/spatial_indexing/tst_quadtree.cc")
env.Program(
    target="algorithms/spatial_indexing/tst_octree", 
    source="algorithms/spatial_indexing/tst_octree.cc")
