
Import('env')

env.SConscript('filter/SConscript', exports={ 'env' : env })
env.SConscript('threshold/SConscript', exports={ 'env' : env })
env.SConscript('centroid/SConscript', exports={ 'env' : env })
env.SConscript('connected_components/SConscript', exports={ 'env' : env })
env.SConscript('fill_holes/SConscript', exports={ 'env' : env })
