
Import('env')

env.SharedLibrary(
    target='#/lib/dials_algorithms_reflexion_basis_ext', 
    source=['boost_python/reflexion_basis_ext.cc'])
    
env.SharedLibrary(
    target='#/lib/dials_algorithms_reflexion_basis_transform_ext', 
    source=['boost_python/transform_ext.cc'])
