
Import('env')

sources = [
    'boost_python/beam.cc',
    'boost_python/detector.cc',
    'boost_python/goniometer.cc',
    'boost_python/equipment_ext.cc']

env.SharedLibrary(target='equipment_ext', source=sources)

