
Import('env')

sources = [
    'boost_python/summed_area.cc',
    'boost_python/mean_and_variance.cc',
    'boost_python/index_of_dispersion_filter.cc',
    'boost_python/convolve.cc',
    'boost_python/median.cc',
    'boost_python/distance.cc',
    'boost_python/anisotropic_diffusion.cc',
    'boost_python/filter_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_image_filter_ext', 
    source=sources,
    LIBS=env["LIBS"])
