Import("env")

env.Program(
    target="algorithms/spot_prediction/tst_reeke_model",
    source="algorithms/spot_prediction/tst_reeke_model.cc",
)
env.Program(
    target="algorithms/spatial_indexing/tst_collision_detection",
    source="algorithms/spatial_indexing/tst_collision_detection.cc",
)
env.Program(
    target="util/tst_thread_pool",
    source="util/tst_thread_pool.cc",
    LIBS=env["LIBS"],
)
