Import("env")

env.Replace(LIBS=[])

env.Program(
    target="algorithms/spot_prediction/tst_reeke_model",
    source="algorithms/spot_prediction/tst_reeke_model.cc",
)
env.Program(
    target="algorithms/spatial_indexing/tst_collision_detection",
    source="algorithms/spatial_indexing/tst_collision_detection.cc",
)
