
Import('env')

sources = [
    'boost_python/mask_code.cc',
    'boost_python/bbox_calculator.cc',
    'boost_python/find_overlapping.cc',
    'boost_python/mask_foreground.cc',
    'boost_python/mask_overlapping.cc',
    'boost_python/mask_builder.cc',
    'boost_python/extractor.cc',
    'boost_python/helpers.cc',
    'boost_python/shoebox_ext.cc']

env.SharedLibrary(
    target='#/lib/dials_algorithms_shoebox_ext', 
    source=sources)
