
Import('env')

sources = [
    'boost_python/mask_code.cc',
    'boost_python/bbox_calculator.cc',
    'boost_python/find_overlapping_reflections.cc',
    'boost_python/masker.cc',
    'boost_python/shoebox_ext.cc']

env.SharedLibrary(
    target='#/lib/dials_algorithms_shoebox_ext', 
    source=sources)
