
Import('env')

sources = [
    'boost_python/lui_find_peak_helper.cc',
    'boost_python/lui_integrate_helper.cc',
    'boost_python/lui_find_peak_smoothing.cc',
    'boost_python/peak_finding_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_peak_finding_ext', 
    source=sources)
