
Import('env')

sources = [
    'boost_python/reflection_mask_roi.cc',
    'boost_python/reflection_mask.cc',
    'boost_python/integration_ext.cc']

env.SharedLibrary(target='#/lib/dials_integration_ext', source=sources)
