Import("env", "env_etc")
import os

sources = ["boost_python/ext.cc"]

ccp4io_lib = getattr(env_etc, "ccp4io_lib", "cmtz")
env.Prepend(LIBS=["cctbx", ccp4io_lib])
if os.name == "nt":
    env.Prepend(LIBS=["Advapi32"])

env.SharedLibrary(target="#/lib/dials_util_ext", source=sources, LIBS=env["LIBS"])
env.SharedLibrary(
    target="#/lib/dials_util_streambuf_test_ext",
    source="boost_python/streambuf_test_ext.cpp",
    LIBS=env["LIBS"],
)
