
Import('env')

sources = [
    'boost_python/xds_coordinate_system.cc',
    'boost_python/geometry_ext.cc']

env.SharedLibrary(target='#/lib/dials_geometry_ext', source=sources)
    
env.SConscript('transform/SConscript', exports={ 'env' : env })
env.SConscript('algorithm/SConscript', exports={ 'env' : env })
