
Import('env')

sources = [
    'boost_python/grid_sampler.cc',
    'boost_python/grid_sampler_2d.cc',
    'boost_python/xds_circle_sampler.cc',
    'boost_python/reference_locator.cc',
    'boost_python/reference_learner.cc',
    'boost_python/reference_learner2d.cc',
    'boost_python/fitting.cc',
    'boost_python/profile_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_integration_profile_ext', 
    source=sources)
