#!/bin/bash

for repository in cctbx_project dxtbx; do
  if [ -e $HOME/build_dials/modules/${repository}/.git ]; then
    echo Cleaning ${repository} repository
    cd $HOME/build_dials/modules/${repository} || exit 1
    git reset --hard HEAD
    git clean -dffxq
  fi
done
