#!/bin/bash

# Identify all python files added or modified in pull request
if [ python -c "import sys;exit(sys.hexversion<0x3000000)" ]; then
  echo Running in Python 3 environment
  CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD -- "*.py")
else
  echo Running in Python 2 environment
  # cut down list of checked files to list of files supporting Python 2
  CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD -- "*.py" | grep -Ff <(cut -c3- .travis/python2-supported-files))
fi

# List is empty if this is not a pull request run or if no python files have changed
[ -z "$CHANGED_FILES" ] && echo There are no relevant changes. Skipping test. && exit 0

pip install -q flake8
echo
echo Running flake8 on changed files
flake8 --select=E401,E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F405,F631,F632,F633,F811,F812,F821,F822,F841,F901,W191,W291,W292,W293,W602,W603,W604,W605,W606 $CHANGED_FILES
