#!/bin/bash

if [ -e $HOME/build_dials/modules/cctbx_project ] && [ ! -e $HOME/build_dials/modules/cctbx_project/.git ]; then
  echo Cleaning existing cctbx_project directory
  rm -rf $HOME/build_dials/modules/cctbx_project
fi

if [ ! -e $HOME/build_dials/modules/cctbx_project ]; then
  echo Cloning cctbx_project from scratch
  git clone https://github.com/cctbx/cctbx_project.git --depth=1 $HOME/build_dials/modules/cctbx_project
fi

echo Checking out latest cctbx_project commit
cd $HOME/build_dials/modules/cctbx_project || exit 1
git fetch origin master --depth=1 || exit 2
git checkout FETCH_HEAD || exit 3
echo CCTBX is at commit:
git show --oneline -s --no-abbrev-commit || exit 4
