
Import('env')

env.SConscript('spot_prediction/SConscript', exports={ 'env' : env })
env.SConscript('integration/SConscript', exports={ 'env' : env })
env.SConscript('spatial_indexing/SConscript', exports={ 'env' : env })
env.SConscript('peak_finding/SConscript', exports={ 'env' : env })
env.SConscript('image/SConscript', exports={ 'env' : env })
env.SConscript('refinement/SConscript', exports={ 'env' : env })
