
Import('env')

env.SConscript('spot_prediction/SConscript', exports={ 'env' : env })
env.SConscript('integration/SConscript', exports={ 'env' : env })
env.SConscript('spatial_indexing/SConscript', exports={ 'env' : env })
