
Import('env')


env.SharedLibrary(target='#/lib/dials_algorithms_background_ext', 
    source = [
      'boost_python/helpers.cc',
      'boost_python/background_ext.cc'
      ],
    LIBS=env["LIBS"])

env.SharedLibrary(target='#/lib/dials_algorithms_background_simple_ext', 
    source = [
      'simple/boost_python/outlier_rejector.cc',
      'simple/boost_python/modeller.cc',
      'simple/boost_python/creator.cc',
      'simple/boost_python/background_simple_ext.cc'
      ],
    LIBS=env["LIBS"])

env.SharedLibrary(target='#/lib/dials_algorithms_background_glm_ext', 
    source = [
      'glm/boost_python/ext.cc'
      ],
    LIBS=env["LIBS"])

env.SharedLibrary(target='#/lib/dials_algorithms_background_const_d_ext', 
    source = [
      'const_d/boost_python/ext.cc'
      ],
    LIBS=env["LIBS"])
