
Import('env')

sources = [
    'boost_python/helpers.cc',
    'boost_python/background_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_background_ext', 
    source=sources,
    LIBS=env["LIBS"])

sources = [
    'simple/boost_python/outlier_rejector.cc',
    'simple/boost_python/modeller.cc',
    'simple/boost_python/creator.cc',
    'simple/boost_python/background_simple_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_background_simple_ext', 
    source=sources,
    LIBS=env["LIBS"])
