
Import('env')

sources = [
    'boost_python/polygon_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_polygon_ext', 
    source=sources)

env.SharedLibrary(
    target='#/lib/dials_algorithms_polygon_areal_interpolation_ext', 
    source='boost_python/areal_interpolation_ext.cc')

env.SConscript('clip/SConscript', exports={ 'env' : env })
