import libtbx.load_env
Import("env_etc")

env_etc.x2tbx_include = libtbx.env.dist_path("x2tbx")
env_etc.cctbx_include = libtbx.env.dist_path("cctbx")

if (not env_etc.no_boost_python and hasattr(env_etc, "boost_adaptbx_include")):
  Import("env_no_includes_boost_python_ext")
  env = env_no_includes_boost_python_ext.Clone()
  env_etc.enable_more_warnings(env=env)
  env_etc.include_registry.append(
    env=env,
    paths=[
      env_etc.libtbx_include,
      env_etc.boost_adaptbx_include,
      env_etc.boost_include,
      env_etc.python_include,
      env_etc.cctbx_include,
      env_etc.x2tbx_include])
  env.SharedLibrary(
    target="#lib/x2tbx_ext",
    source=["ext.cpp", "x2tbx.cpp", "x2tbx_ol.cpp", "x2tbx_rl.cpp"])
