
Import('env')

sources = [
    'boost_python/centroid.cc',
    'boost_python/masked_centroid.cc',
    'boost_python/centroid_list.cc',
    'boost_python/centroid_ext.cc']

env.SharedLibrary(target='#/lib/dials_algorithms_image_centroid_ext', 
    source=sources)
