
Import('env')

Import("env_base", "env_etc")

env.SharedLibrary(
    target='#/lib/dials_algorithms_profile_model_gaussian_rs_ext',
    source=[
      'gaussian_rs/boost_python/gaussian_rs_ext.cc'
    ])

env.SharedLibrary(
    target='#/lib/dials_algorithms_profile_model_gaussian_rs_transform_ext',
    source=[
      'gaussian_rs/transform/boost_python/transform_ext.cc',
    ])
