Import("env")

Import("env_base", "env_etc")

env.SharedLibrary(
    target="#/lib/dials_algorithms_profile_model_modeller_ext",
    source=[
        "modeller/boost_python/sampler.cc",
        "modeller/boost_python/modeller.cc",
        "modeller/boost_python/ext.cc",
    ],
    LIBS=env["LIBS"],
)

env.SharedLibrary(
    target="#/lib/dials_algorithms_profile_model_gaussian_rs_ext",
    source=["gaussian_rs/boost_python/gaussian_rs_ext.cc"],
    LIBS=env["LIBS"],
)

env.SharedLibrary(
    target="#/lib/dials_algorithms_profile_model_gaussian_rs_transform_ext",
    source=["gaussian_rs/transform/boost_python/transform_ext.cc"],
    LIBS=env["LIBS"],
)

env.SharedLibrary(
    target="#/lib/dials_algorithms_profile_model_potato_ext",
    source=["potato/boost_python/ext.cc"],
    LIBS=env["LIBS"],
)
